
exports.updater=(req,res,model)=>{
  if(req.body.cpi!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"cpi":req.body.cpi}},(err,response)=>{
    })
  }
  if(req.body.Internexp!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"Internexp":req.body.Internexp}},(err,response)=>{
    })
  }
  if(req.body.Internchoice!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"Internchoice":req.body.Internchoice}},(err,response)=>{
    })
  }
  if(req.body.boardmarks!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"boardmarks":req.body.boardmarks}},(err,response)=>{
    })
  }
  if(req.body.metricmarks!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"metricmarks":req.body.metricmarks}},(err,response)=>{
    })
  }
  if(req.body.internpref1!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"internpref1":req.body.internpref1}},(err,response)=>{
    })
  }
  if(req.body.internpref2!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"internpref2":req.body.internpref2}},(err,response)=>{
    })
  }
  if(req.body.internpref3!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"internpref3":req.body.internpref3}},(err,response)=>{
    })
  }
  if(req.body.internpref4!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"internpref4":req.body.internpref4}},(err,response)=>{
    })
  }
  if(req.body.software!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"software":req.body.software}},(err,response)=>{
    })
  }
  if(req.body.personalskills!='')
  {
    model.findOneAndUpdate({"username":req.session.user.username},{$set:{"personalskills":req.body.personalskills}},(err,response)=>{
    })
  }
  res.redirect('/dashboard')
}
